### ISSUE TITLE
Python 2 compatibility 

### ISSUE THREAD

**Issue by Peter554** [Peter554/StainTools#19]
Does anybody want to do some compatibility tests for Python 2? Presently only really checked on Python 3 (3.5). I've added `from __future__ import division` to most of the files but this may not be enough..

**Comment by ghost** [comment]
I'm currently working on this. (No guarantees!)
One question, there's a [`future`](https://python-future.org/) package in [`setup.py`'s dependency list](https://github.com/Peter554/StainTools/blob/master/setup.py#L19); Is it intentional? i.e. Shall I use this library for python2 support?

**Edit**
Okay, just [fixed two small glitches](https://github.com/Scorbie/StainTools/commit/2765e2dbd3acf7a9e7eb8def65ee5e9e180efe0d) and Jupyter Notebook demos work on python2.7.
1. Haven't used any external packages (no `six`, no `future`) when using `ABC`s in python2, but I'll use it if that is the recommended style for this repo.
2. Willing to test more examples / send you a pull request upon request.

**Comment by ghost** [comment]
Python 2 support update
---
Well, this time I needed to tweak setup.py **considerably** to make it work on a fresh python2.7 virtualenv install. (I guess I was working inside conda last time)

Anyway, it works now, so if anyone needs python2 support real quick, one can probably use:
`pip install git+https://github.com/Scorbie/StainTools.git#egg=staintools`

---
I'm not issuing a pull request right now, as [`setup.py`](https://github.com/Scorbie/StainTools/commit/a611535d53a345f7b31ac9d56d5ceaf568c1a098)  became a little bloated to address all the version clashes for jupyter. Manually editing all this takes quite some time, and I'm not sure if I can maintain this when this breaks again. (Let's just hope it doesn't...)

---
Also, regarding #24, what do you think of
1. Removing unused dependencies?
  :wastebasket: `cython` `future` (which is different from `__future__` btw)
2.  Moving `jupyter` (and friends) to dev-dependencies?
  Just because with a normal pip install, the examples are not available, and <br>people wanting source code have to install with `setup.py develop` anyway.
