### ISSUE TITLE
AssertionError: Negative optical density.

### ISSUE THREAD

**Issue by hasibzunair** [Peter554/StainTools#33]
Had a few issues while using this library. They are as follows:

* Installation issue(spams error)
* Running stain normalization on a batch if 15000 images resulted in the Negative optical density error.

Looking forward to a fix. Thanks.

**Comment by Peter554** [comment]
Lets track the pip install issue here #32.

In terms of the negative optical density issue can you provide more details.

- Do you have a stack trace?
- Which algorithm were you using (macenko or vahadane)?
- Can you provide an example failure image and script to run?
- How negative were the OD values?

**Comment by hasibzunair** [comment]
Vahadane algorithm was used for stain normalization. The stack trace is given below:

```
/usr/local/lib/python3.6/dist-packages/staintools/stain_normalizer.py:41: RuntimeWarning: invalid value encountered in true_divide
  source_concentrations *= (self.maxC_target / maxC_source)
/usr/local/lib/python3.6/dist-packages/staintools/miscellaneous/miscellaneous_functions.py:26: RuntimeWarning: invalid value encountered in true_divide
  return A / np.linalg.norm(A, axis=1)[:, None]
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-18-636ad9ad5400> in <module>()
      3 
      4 for i in x_train[:]:
----> 5   img = stain_normalize(i)
      6   x_train_st.append(img)
      7   #print(count)

<ipython-input-15-66a64e10eb9f> in stain_normalize(img)
     13   # Stain normalize
     14   normalizer = staintools.StainNormalizer(method='vahadane')
---> 15   normalizer.fit(target)
     16   transformed = normalizer.transform(to_transform)
     17   return transformed

/usr/local/lib/python3.6/dist-packages/staintools/stain_normalizer.py in fit(self, target)
     27         self.target_concentrations = get_concentrations(target, self.stain_matrix_target)
     28         self.maxC_target = np.percentile(self.target_concentrations, 99, axis=0).reshape((1, 2))
---> 29         self.stain_matrix_target_RGB = convert_OD_to_RGB(self.stain_matrix_target)  # useful to visualize.
     30 
     31     def transform(self, I):

/usr/local/lib/python3.6/dist-packages/staintools/miscellaneous/optical_density_conversion.py in convert_OD_to_RGB(OD)
     25     :return: Image RGB uint8.
     26     """
---> 27     assert OD.min() >= 0, "Negative optical density."
     28     OD = np.maximum(OD, 1e-6)
     29     return (255 * np.exp(-1 * OD)).astype(np.uint8)

AssertionError: Negative optical density.
```

**Comment by hasibzunair** [comment]
Th code: 

```
def stain_normalize(img):
  
  '''Return the image with the stain removed, probably...'''
  
  # here, both are same image
  target = img
  to_transform = img

  # Standardize brightness (This step is optional but can improve the tissue mask calculation)
  target = staintools.LuminosityStandardizer.standardize(target)
  to_transform = staintools.LuminosityStandardizer.standardize(to_transform)

  # Stain normalize
  normalizer = staintools.StainNormalizer(method='vahadane')
  normalizer.fit(target)
  transformed = normalizer.transform(to_transform)
  return transformed



x_train_st =[] # store normalize images here
count = 0

# x_train is of shape (27588, 200, 200, 3)

for i in x_train[:]:
  img = stain_normalize(i)
  x_train_st.append(img)
  #print(count)
  #count+=1
    
x_train_st = np.array(x_train_st)
x_train_st.shape
```

**Comment by Peter554** [comment]
Seems odd. I wonder is there anything atypical about the images for which the method is failing (all white, all black)?

I assume the x_train images are all uint8?

On another note you seem to be fitting and transforming to the same `img`. I'm not quite sure of the point here. If the library is working correctly you should just get back the original image?

**Comment by hasibzunair** [comment]
Will check the image(s) were the error occurred. Fitting and transforming to the same image results in this: 

![image](https://user-images.githubusercontent.com/33185386/54751881-75b7b800-4c06-11e9-98a7-59dbb6bda08b.png)

**Comment by Peter554** [comment]
Well this image is not really typical of an image where the algorithms will perform well. Thinking just about stain extraction any pixel in an ideal H&E image should have its color composed from a combination of the two basis stains (H & E). The original image above (left) looks to have no/very-little Hematoxylin (would be purplish) and therefore the algorithm will not be able to accurately determine the stains and will therefore probably not do much sensible.

In practice most real images also have some background which will be white/light-gray. To accurately determine the stain colors these pixels should be removed before stain extraction. The current stain-normalizer implementation tries to remove these by filtering on the luminosity (I think currentlyit uses a fixed value of 0.8). So pixels with a luminosity higher than the threshold are considered background and are ignored for stain extraction. This can lead to the final image not looking exactly like the original, but for typical images the difference shouldn't be substantial. 

I see you are using the brightness-standardising step first. This is intended for images which are dim and where the background is significantly grey. The idea is to try and make the background close to white in order to help segment the tissue and remove the background. For the image above though it would essentially make the entire image white as the image is very uniform in color and (assuming that really is tissue and not background) that would therefore be an error as when we then try to identify the tissue and extract from the background we will get almost nothing back.

I see there is also what looks like a black segmentation mask around the image. That will also cause problems in determining the stains in the image.

**Comment by hasibzunair** [comment]
@Peter554  What would you suggest I do? 
Can you also give me a requirements.txt file from you end, so that I can make a separate environment using that?

**Comment by Peter554** [comment]
Regarding requirements please consult the [setup.py](https://github.com/Peter554/StainTools/blob/master/setup.py).

Perhaps have a look inside [stain_normalizer.py](https://github.com/Peter554/StainTools/blob/master/staintools/stain_normalizer.py). This is basically a wrapper for a few simple steps e.g. extract stains, get concentrations. If you just do the steps directly you could override the default value for the luminosity threshold (this is an input to stain_extractor). For that image above you would want not to standardize the brightness using my crude method. Have a think about your set of images as a whole and perhaps you may be able to come up with something better? The library source code is not long so maybe just have a look inside and just take what works for you.

On the other hand if you have such a large dataset I wouldn't necessarily advise bothering with stain normalization. If you're doing something like deep learning you may just be better off and save a lot of preprocessing time to apply some on the fly color augmentation #29.

**Comment by Peter554** [comment]
Going back to the original issue though. Even though I wouldn't expect the algorithm to work very well on the image above, I'm still not quite sure why this negative optical density is occurring. If I work it out I'll let you know.

**Comment by hasibzunair** [comment]
Alright, thank you for your help.
